import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import BottomNav from "@/components/ui/bottomnav";
import SessionProvider from "@/components/ui/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getServerSession();
  return (
    <html data-theme="dim" lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <main>
            <header>
              <Navbar />
            </header>
            {children}
            <BottomNav />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
